apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodeport: 31380
      targetPort: 80